import './Company.css';
import Layout from '../components/layout';
import { StarIcon } from '@heroicons/react/outline';
import Rating from '../components/rating';
import SeeMore from '../components/seeMore';
import CharacteristicRating from '../components/characteristicRating';

const experienceRatings = [
  { name: 'Work-life balance' },
  { name: 'Remote flexibility' },
  { name: 'Diversity' },
  { name: 'Inclusive environment' },
  { name: 'Trust' },
  { name: 'Young & fun environment' },
];

const personalRatings = [
  { name: 'Growth opportunies' },
  { name: 'Mentorship' },
  { name: 'Work Satisfaction' },
  { name: 'Team support' },
  { name: 'Managerial Support' },
  { name: 'Collaborative environment' },
  { name: 'Diverse leadership' },
];

const traditionalRatings = [
  { name: 'Compensation' },
  { name: 'Benefits & perks' },
  { name: 'Personal/ vacation time' },
  { name: 'Job security' },
  { name: 'Executive team' },
  { name: 'Interview process' },
];

const Company = () => {
  return (
    <Layout>
      <div className="company-container grid grid-cols-2 mb-16">
        <div className="company-card justify-start">
          <img src="/images/company-image.svg" className="company-image" />
          <p className='company-name-section mt-6'>IBM North America</p>
          <div className="company-rating grid grid-cols-2 justify-between mt-4 w-72">
            <div className="company-rating-stars mt-1">
              <Rating />
            </div>
            <div className="company-rating-text text-sm">
              <p>5/5 average rating</p>
            </div>
          </div>
          <div className="company-review-total text-sm mt-4">
            <p>Total Reviews: 147</p>
          </div>
        </div>
        <div className="company-information-container justify-end max-w-sm">
          <SeeMore>
            <p>International Business Machines Corporation (IBM) is an American multinational technology corporation headquartered in Armonk, New York, with operations in over 171 countries.
              IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most annual U.S. patents generated by a business (as of 2020) for 28 consecutive years.
              Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM). The IBM mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and 70s.
              https://www.ibm.com/
            </p>
          </SeeMore>
          <button type="button" className="mt-5 inline-flex justify-self-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            <StarIcon className="-ml-1 mr-2 h-5 w-5 bg-200" aria-hidden="true" />
            Rate this company
          </button>
        </div>
      </div>
      <div className="cultural-characteristics-container rounded-lg py-9 px-12">
        <h1 className="text-3xl font-semibold">Cultural workplace characteristics</h1>
        <CharacteristicRating characteristic="WORKPLACE EXPERIENCE" ratings={experienceRatings} />
        <CharacteristicRating characteristic="PERSONAL GROWTH" ratings={personalRatings} />
      </div>
      <div className="traditional-characteristics-container rounded-lg py-9 px-12 mt-14">
        <h1 className="text-3xl font-semibold">Traditional workplace characteristics</h1>
        <CharacteristicRating ratings={traditionalRatings} />
      </div>
      <div className="question-company mt-20">
        <h1 className="text-2xl font-semibold mb-8">Do you work at IBM North America?</h1>
        <p className="text-lg font-normal mb-8 max-w-xl">By honestly rating your company, you can help other job seekers.  Our system is completely anoymous after email verification.</p>
        <button type="button" className="mt-5 inline-flex justify-self-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
          <StarIcon className="-ml-1 mr-2 h-5 w-5 bg-200" aria-hidden="true" />
          Rate this company
        </button>
      </div>
    </Layout>
  );
}

export default Company;
